diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: left_wheel_joint
  right_wheel: right_wheel_joint
  publish_rate: 50
  wheel_separation: 0.38
  wheel_radius: 0.1
  cmd_vel_timeout: 0.25
  enable_odom_tf: true
